djangotest/App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^index/', views.index, name='index'),

#teacher
    url(r'^login_teacher/', views.login_teacher, name='login_teacher'),
    url(r'^register_teacher/', views.register_teacher, name='register_teacher'),
    url(r'^reset_teacher/', views.reset_teacher, name='reset_teacher'),
    url(r'^teacher_home/', views.teacher_home, name='teacher_home'),
    url(r'^logout_teacher/', views.logout_teacher, name='logout_teacher'),
    url(r'^resetteacher/', views.resetteacher, name='resetteacher'),


#student
    url(r'^login_student/', views.login_student, name='login_student'),
    url(r'^student_home/', views.student_home, name='student_home'),
    url(r'^logout_student/', views.logout_student, name='logout_student'),
    url(r'^reset_student/', views.reset_student, name='reset_student'),
    url(r'^resetstudent/', views.resetstudent, name='resetstudent'),

    url(r'^checktid/', views.checktid, name='checktid'),

    url(r'^activate/', views.activate, name='activate'),
    url(r'^reactivate/', views.reactivate, name='reactivate'),


    # url(r'^checktlogint/$', views.checklogint, name='checklogint'),
    # url(r'send_email/', views.send_email, name='send_email'),




]

djangotest/ZXY/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import xadmin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),

    url(r'^zxy/', include('App.urls', namespace='zxy')),
]

djangotest/templates/activate.html
<h4>亲爱的{{ teacher_name }}老师：</h4>
<p style="text-indent: 2em;">
欢迎使用智学云——教学办公一体化平台！但您的账号还没有进行激活认证，请在24小时之内点击下面的激活链接进行激活！
</p>
<button><a href="{{ activate_url }}">激活</a></button>
<P>若上面的激活按钮无法使用，请将下面的地址复制到浏览器进行激活！</P>
<P>{{ activate_url }}</P>
<hr>
<h6>以上内容请勿泄露给他人，如非本人操作，请忽略此信息！</h6>
<h6>Tips:*本消息来自智学云——教学办公一体化平台！</h6>

djangotest/templates/activation_failed.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{{ title }}</title>
		<script type="text/javascript" src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
		<link type="text/css" rel="stylesheet" href="{% static 'bootstrap3/css/bootstrap.min.css' %}" />
		<script type="text/javascript" src="{% static 'bootstrap3/js/bootstrap.min.js' %}"></script>
		<style>
			.button {
				/* align="center"; */
			    background-color: #008CBA;
			    border: 2px solid #555555;
			    color: white;
			    padding: 15px 32px;
			    text-align: center;
			    text-decoration: none;
			    display: inline-block;
			    font-size: 24px;
				border-radius: 12px;
			}
			#reactivate{
				color: white;
			}
			h1{
				color: #B92C28;
			}
			#header{
				background-color: #96b97d;
			}
		</style>
	</head>

	<body>
<!--header-->
		<div class="jumbotron text-center" style="margin-bottom:0" id="header">
			<h1>欢迎使用智学云——教学办公一体化平台！</h1>
			<p>让教学办公更简便！</p>
		</div>
<!--context-->
		<h1 align="center" >{{ content }}！</h1>
		<div style="text-align: center;" id="context">
		<button type="button" class="button"><a href="{% url 'zxy:reactivate' %}" id="reactivate">重新激活</a></button>
		</div>
		<hr/>
<!--footer-->
		<footer class="footer">
			<div class="container">
				<div class="row footer-top">
					<div class="col-md-6 col-lg-6">
						<h4>
							<img src="{% static 'img/YNULogo.png' %}" alt="">
							<strong>智学云——教学办公一体化平台</strong>
						</h4>
						<p>我们一直致力于为广大师生提供更多的优质服务！</p>
					</div>
					<div class="col-md-6  col-lg-6">
						<div class="row about">
							<div class="col-sm-3">
								<h4>关于</h4>
								<ul class="list-unstyled">
									<li><a href="#">关于我们</a></li>
									<li><a href="#">广告合作</a></li>
									<li><a href="#">友情链接</a></li>
									<li><a href="#">招聘</a></li>
								</ul>
							</div>
							<div class="col-sm-3">
								<h4>联系方式</h4>
								<ul class="list-unstyled">
									<li><a href="#">
											<!-- "https://weibo.com/bootcss" title="Bootstrap中文网官方微博" -->
											<!-- target="_blank"> -->新浪微博</a></li>
									<li><a href="#">
											<!-- "mailto:admin@bootcss.com"> -->电子邮件</a></li>
								</ul>
							</div>
							<div class="col-sm-3">
								<h4>旗下网站</h4>
								<ul class="list-unstyled">
									<li><a href="#">
											<!-- "https://www.bootcdn.cn/" target="_blank"> -->xxxxxxxx</a></li>
									<li><a href="#">
											<!-- "https://pkg.phpcomposer.com/" target="_blank"> -->xxxxxxxx</a></li>
								</ul>
							</div>
							<div class="col-sm-3">
								<h4>特别致谢</h4>
								<ul class="list-unstyled">
									<li><a href="#">
											<!-- "https://www.maoyuncloud.com/" target="_blank"> -->xxxxxxxx</a></li>

								</ul>
							</div>
						</div>

					</div>
				</div>
				<hr />
				<div class="row footer-bottom">
					<ul class="list-inline text-center">
						<li><a href="#">
								<!-- "https://beian.miit.gov.cn/" target="_blank"> -->京ICP备xxxxxxxx号-x</a></li>
						<li>京公网安备xxxxxxxxxxxxxx</li>
					</ul>
				</div>
			</div>
		</footer>
	</body>
</html>

djangotest/templates/login_student.html
<!doctype html>
{% load static %}
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>智学云</title>
		<script type="text/javascript" src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
		<link type="text/css" rel="stylesheet" href="{% static 'bootstrap3/css/bootstrap.min.css' %}" />
		<script type="text/javascript" src="{% static 'bootstrap3/js/bootstrap.min.js' %}"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />
		<script src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
		<link href="{% static 'css/footer.css' %}" rel="stylesheet">
		<link href="{% static 'css/ver_code.css' %}" rel="stylesheet" />
		<script src="{% static 'js/md5.js' %}"></script>
		<script src="{% static 'js/ver_code.js' %}"></script>
		<script src="{% static 'js/login_student.js' %}"></script>
		<script src="{% static 'js/check_login_s.js' %}"></script>
	</head>
	<body>
		<nav class="navbar navbar-inverse" role="navigation" style="margin-bottom:0">
			<div class="container-fluid">
				<div class="navbar-header col-md-3">
					<a class="navbar-brand" href="javascript:void(0)">智学云——教学办公一体化系统</a>
				</div>
				<div class="col-md-offset-8">
					<ul class="nav navbar-nav">
						<li><a href="{% url 'zxy:login_teacher' %}"><b class="glyphicon glyphicon-user"></b>教师登录</a></li>
						<li class="active"><a href="{% url 'zxy:login_student' %}"><b class="glyphicon glyphicon-user"></b>学生登录</a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								关于
								<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><a href="/xadmin/">后台管理员登录</a></li>
								<li class="divider"></li>
								<li><a href="#">联系我们</a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		<div class="jumbotron text-center" id="header">
			<h1>欢迎使用智学云——教学办公一体化平台！</h1>
			<!-- <p>教师登录页面</p> -->
		</div>
		<div class="wrap flex-c-c">
			<!-- <h1 class="welcome">欢迎使用智学云——教学办公一体化系统!</h1> -->
			<form action="{% url 'zxy:login_student' %}" method="post" class="flex-c-c" onsubmit="return check_login_s()">
				{% csrf_token %}
				<h1 class="warning">学生登录页面</h1>
				<ul class="select__list">
					<li id="js-usr-rtn" class="select__label select__label--active"><a href="{% url 'zxy:login_student' %}">登录</a></li>
					<li id="none" class="select__label">&nbsp &nbsp </li>
					<li id="js-usr-rst" class="select__label"><a href="{% url 'zxy:reset_student' %}">忘记密码</a></li>
				</ul>
				<span class="pointer --usr-rtn"></span>
				<input type="number" name="studentid" placeholder="学号" class="ui-field" id="js-field__id" required="required"/>
				<span class="error" id="id_error"></span>
				<input type="password" name="studentpaw" placeholder="密码" class="ui-field" id="js-field__pass" required="required"/>
				<span class="error" id="pass_error"></span>
				<input type="text" value="" placeholder="请输入验证码（不区分大小写）" class="input-val" required="required">
				<span class="error text-center" id="vc_error"></span>
				<canvas class="center-block" id="canvas" width="100" height="30"></canvas>
				<button id="js-btn" class="ver_code ui-button --usr-rtn" type="submit"></button>
				<a href="{% url 'zxy:login_teacher' %}" class="btn btn-primary" id="transfer">进入教师登录页面</a>
			</form>
		</div>
		<footer class="bs-docs-footer">
				  <div class="container">
				    <ul class="bs-docs-footer-links">
				      <li><a href="http://www.ynu.edu.cn">云南大学</a></li>
				      <li><a href="#">联系我们</a></li>
				      <li><a href="#">关于</a></li>
				    </ul>
					<h4>
					  <strong>智学云——教学办公一体化平台</strong>
					</h4>
				    <p>我们一直致力于为广大师生提供更多的优质服务！</p>
				
				    <!-- <p>Code licensed <a href="https://github.com/twbs/bootstrap/blob/v3-dev/LICENSE" rel="license noopener" target="_blank">MIT</a>, docs <a href="https://creativecommons.org/licenses/by/3.0/" rel="license noopener" target="_blank">CC BY 3.0</a>.</p> -->
				
				  </div>
				</footer>
	</body>
</html>

djangotest/templates/login_teacher.html
<!doctype html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>智学云</title>
	<script type="text/javascript" src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
	<link type="text/css" rel="stylesheet" href="{% static 'bootstrap3/css/bootstrap.min.css' %}" />
	<script type="text/javascript" src="{% static 'bootstrap3/js/bootstrap.min.js' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />
	<script src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
	<link href="{% static 'css/footer.css' %}" rel="stylesheet" />
	<link href="{% static 'css/ver_code.css' %}" rel="stylesheet" />
	<script src="{% static 'js/md5.js' %}"></script>
	<script src="{% static 'js/ver_code.js' %}"></script>
    <script src="{% static 'js/login_teacher.js' %}"></script>
<!--	<script src="{% static 'js/login_t.js' %}"></script>-->
	<script src="{% static 'js/check_login_t.js' %}"></script>
<body>
<nav class="navbar navbar-inverse" role="navigation" style="margin-bottom:0">
			<div class="container-fluid">
			<div class="navbar-header col-md-3">
				<a class="navbar-brand" href="javascript:void(0))">智学云——教学办公一体化系统</a>
			</div>
			<div class="col-md-offset-8">
				<ul class="nav navbar-nav">
					<li class="active"><a href="{% url 'zxy:login_teacher' %}"><b class="glyphicon glyphicon-user"></b>教师登录</a></li>
					<li><a href="{% url 'zxy:login_student' %}"><b class="glyphicon glyphicon-user"></b>学生登录</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							关于
							<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><a href="/xadmin/">后台管理员登录</a></li>
							<li class="divider"></li>
							<li><a href="#">联系我们</a></li>
							<!-- <li class="divider"></li> -->
							<!-- <li><a href="#">Jasper Report</a></li>
							<li><a href="#">分离的链接</a></li>
							<li><a href="#">另一个分离的链接</a></li> -->
						</ul>
					</li>
				</ul>
			</div>
			</div>
		</nav>
		<div class="jumbotron text-center" id="header">
			<h1>欢迎使用智学云——教学办公一体化平台！</h1>
			<!-- <p>教师登录页面</p> -->
		</div>
<div class="wrap flex-c-c">
<!-- <h1 class="welcome">欢迎使用智学云——教学办公一体化系统!</h1> -->
  <form action="{% url 'zxy:login_teacher' %}" method="post" class="flex-c-c" onsubmit="return check_login_t()">
	  {% csrf_token %}

	<h1 class="warning">教师登录页面</h1>
    <ul class="select__list">
      <li id="js-usr-rtn" class="select__label select__label--active"><a href="{% url 'zxy:login_teacher' %}">登录</a></li>
      <li id="js-usr-new" class="select__label"><a href="{% url 'zxy:register_teacher' %}">注册</a></li>
      <li id="js-usr-rst" class="select__label"><a href="{% url 'zxy:reset_teacher' %}">忘记密码</a></li>
    </ul>
    <span class="pointer --usr-rtn"></span>
<!--	<input type="text" placeholder="真实姓名" class="ui-field" id="js-field__name" required="required"/>-->
<!--      <span class="error" id="name_error"></span>-->
    <input type="number" name="teacherid" placeholder="职工号" class="ui-field" id="js-field__id" required="required"/>
      <span class="error" id="id_error"></span>
<!--	<input type="email" placeholder="邮箱" class="ui-field" id="js-field__email" required="required"/>-->
<!--      <span class="error" id="email_error"></span>-->
    <input type="password" name="teacherpaw" placeholder="密码" class="ui-field" id="js-field__pass" required="required"/>
      <span class="error" id="pass_error"></span>
<!--    <input type="password" placeholder="确认密码" class="ui-field ui-field&#45;&#45;hidden" id="js-field__r-pass" required="required"/>-->
<!--      <span class="error" id="r-pass_error"></span>-->

	  <input type="text" value="" placeholder="请输入验证码（不区分大小写）" class="input-val" required="required"/>
	  <span class="error text-center" id="vc_error"></span>
	  <canvas class="center-block" id="canvas" width="100" height="30"></canvas>
	        <!-- <button class="btn btn-primary">提交</button> -->

    <button id="js-btn" class="vcbtn ui-button --usr-rtn" type="submit"></button>
	<a href="{% url 'zxy:login_student' %}" class="btn btn-primary" id="transfer">进入学生登录页面</a>
  </form>
</div>
<footer class="bs-docs-footer">
		  <div class="container">
		    <ul class="bs-docs-footer-links">
		      <li><a href="http://www.ynu.edu.cn">云南大学</a></li>
		      <li><a href="#">联系我们</a></li>
		      <li><a href="#">关于</a></li>
		    </ul>
			<h4>
			  <strong>智学云——教学办公一体化平台</strong>
			</h4>
		    <p>我们一直致力于为广大师生提供更多的优质服务！</p>
		
		    <!-- <p>Code licensed <a href="https://github.com/twbs/bootstrap/blob/v3-dev/LICENSE" rel="license noopener" target="_blank">MIT</a>, docs <a href="https://creativecommons.org/licenses/by/3.0/" rel="license noopener" target="_blank">CC BY 3.0</a>.</p> -->
		
		  </div>
		</footer>

</body>
</html>

djangotest/templates/register_teacher.html
<!doctype html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>智学云</title>
	<script type="text/javascript" src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
	<link type="text/css" rel="stylesheet" href="{% static 'bootstrap3/css/bootstrap.min.css' %}" />
	<script type="text/javascript" src="{% static 'bootstrap3/js/bootstrap.min.js' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />
	<script src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
	<link href="{% static 'css/footer.css' %}" rel="stylesheet" />
	<link href="{% static 'css/ver_code.css' %}" rel="stylesheet" />
	<script src="{% static 'js/md5.js' %}"></script>
	<script src="{% static 'js/ver_code.js' %}"></script>
    <script src="{% static 'js/login_teacher.js' %}"></script>
	<script src="{% static 'js/register_t.js' %}"></script>
	<script src="{% static 'js/check_register.js' %}"></script>

<body>
<nav class="navbar navbar-inverse" role="navigation" style="margin-bottom:0">
			<div class="container-fluid">
			<div class="navbar-header col-md-3">
				<a class="navbar-brand" href="javascript:void(0))">智学云——教学办公一体化系统</a>
			</div>
			<div class="col-md-offset-8">
				<ul class="nav navbar-nav">
					<li class="active"><a href="{% url 'zxy:login_teacher' %}"><b class="glyphicon glyphicon-user"></b>教师登录</a></li>
					<li><a href="{% url 'zxy:login_student' %}"><b class="glyphicon glyphicon-user"></b>学生登录</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							关于
							<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><a href="/xadmin/">后台管理员登录</a></li>
							<li class="divider"></li>
							<li><a href="#">联系我们</a></li>
							<!-- <li class="divider"></li> -->
							<!-- <li><a href="#">Jasper Report</a></li>
							<li><a href="#">分离的链接</a></li>
							<li><a href="#">另一个分离的链接</a></li> -->
						</ul>
					</li>
				</ul>
			</div>
			</div>
		</nav>
		<div class="jumbotron text-center" id="header">
			<h1>欢迎使用智学云——教学办公一体化平台！</h1>
			<!-- <p>教师登录页面</p> -->
		</div>
<div class="wrap flex-c-c">
<!-- <h1 class="welcome">欢迎使用智学云——教学办公一体化系统!</h1> -->
  <form action="{% url 'zxy:register_teacher' %}" method="post" class="flex-c-c" onsubmit="return check_register()">

	  {% csrf_token %}

	<h1 class="warning">教师登录页面</h1>
    <ul class="select__list">
      <li id="js-usr-rtn" class="select__label"><a href="{% url 'zxy:login_teacher' %}">登录</a></li>
      <li id="js-usr-new" class="select__label select__label--active"><a href="{% url 'zxy:register_teacher' %}">注册</a></li>
      <li id="js-usr-rst" class="select__label"><a href="{% url 'zxy:reset_teacher' %}">忘记密码</a></li>
    </ul>
    <span class="pointer --usr-new"></span>
	<input type="text" name="teachername" placeholder="真实姓名" class="ui-field" id="js-field__name" required="required"/>
      <span class="error" id="name_error"></span>
    <input type="number" name="teacherid" placeholder="职工号" class="ui-field" id="js-field__id" required="required"/>
      <span class="error" id="id_error"></span>
	<input type="email" name="teacheremail" placeholder="邮箱" class="ui-field" id="js-field__email" required="required"/>
      <span class="error" id="email_error"></span>
    <input type="password" name="teacherpaw" placeholder="密码" class="ui-field" id="js-field__pass" required="required"/>
      <span class="error" id="pass_error"></span>
    <input type="password" placeholder="确认密码" class="ui-field" id="js-field__r-pass" required="required"/>
      <span class="error" id="r-pass_error"></span>
	<input type="text" value="" placeholder="请输入验证码（不区分大小写）" class="input-val" required="required"/>
	  <span class="error text-center" id="vc_error"></span>
	<canvas class="center-block" id="canvas" width="100" height="30"></canvas>

    <button id="js-btn" class="vcbtn ui-button --usr-new" type="submit"></button>
	<a href="{% url 'zxy:login_student' %}" class="btn btn-primary" id="transfer">进入学生登录页面</a>
  </form>
</div>
<footer class="bs-docs-footer">
		  <div class="container">
		    <ul class="bs-docs-footer-links">
		      <li><a href="http://www.ynu.edu.cn">云南大学</a></li>
		      <li><a href="#">联系我们</a></li>
		      <li><a href="#">关于</a></li>
		    </ul>
			<h4>
			  <strong>智学云——教学办公一体化平台</strong>
			</h4>
		    <p>我们一直致力于为广大师生提供更多的优质服务！</p>

		    <!-- <p>Code licensed <a href="https://github.com/twbs/bootstrap/blob/v3-dev/LICENSE" rel="license noopener" target="_blank">MIT</a>, docs <a href="https://creativecommons.org/licenses/by/3.0/" rel="license noopener" target="_blank">CC BY 3.0</a>.</p> -->

		  </div>
		</footer>

</body>
</html>

djangotest/templates/reset_s.html
<h4>亲爱的{{ student_name }}同学：</h4>
<p style="text-indent: 2em;">
欢迎使用智学云——教学办公一体化平台！请在24小时之内点击下面的密码重置按钮进行密码重置！
</p>
<button><a href="{{ reset_url }}">密码重置</a></button>
<P>若上面的密码重置按钮无法使用，请将下面的地址复制到浏览器进行密码重置！</P>
<P>{{ reset_url }}</P>
<hr>
<h6>以上内容请勿泄露给他人，如非本人操作，请忽略此信息！</h6>
<h6>Tips:*本消息来自智学云——教学办公一体化平台！</h6>

djangotest/templates/reset_t.html
<h4>亲爱的{{ teacher_name }}老师：</h4>
<p style="text-indent: 2em;">
欢迎使用智学云——教学办公一体化平台！请在24小时之内点击下面的密码重置按钮进行密码重置！
</p>
<button><a href="{{ reset_url }}">密码重置</a></button>
<P>若上面的密码重置按钮无法使用，请将下面的地址复制到浏览器进行密码重置！</P>
<P>{{ reset_url }}</P>
<hr>
<h6>以上内容请勿泄露给他人，如非本人操作，请忽略此信息！</h6>
<h6>Tips:*本消息来自智学云——教学办公一体化平台！</h6>

djangotest/templates/reset_teacher.html
<!doctype html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>智学云</title>
	<script type="text/javascript" src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
	<link type="text/css" rel="stylesheet" href="{% static 'bootstrap3/css/bootstrap.min.css' %}" />
	<script type="text/javascript" src="{% static 'bootstrap3/js/bootstrap.min.js' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />
	<script src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
	<link href="{% static 'css/footer.css' %}" rel="stylesheet" />
	<link href="{% static 'css/ver_code.css' %}" rel="stylesheet" />
	<script src="{% static 'js/md5.js' %}"></script>
	<script src="{% static 'js/ver_code.js' %}"></script>
    <script src="{% static 'js/login_teacher.js' %}"></script>
	<script src="{% static 'js/check_reset_t.js' %}"></script>
<body>
<nav class="navbar navbar-inverse" role="navigation" style="margin-bottom:0">
			<div class="container-fluid">
			<div class="navbar-header col-md-3">
				<a class="navbar-brand" href="javascript:void(0))">智学云——教学办公一体化系统</a>
			</div>
			<div class="col-md-offset-8">
				<ul class="nav navbar-nav">
					<li class="active"><a href="{% url 'zxy:login_teacher' %}"><b class="glyphicon glyphicon-user"></b>教师登录</a></li>
					<li><a href="{% url 'zxy:login_student' %}"><b class="glyphicon glyphicon-user"></b>学生登录</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							关于
							<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><a href="/xadmin/">后台管理员登录</a></li>
							<li class="divider"></li>
							<li><a href="#">联系我们</a></li>
						</ul>
					</li>
				</ul>
			</div>
			</div>
		</nav>
		<div class="jumbotron text-center" id="header">
			<h1>欢迎使用智学云——教学办公一体化平台！</h1>
			<!-- <p>教师登录页面</p> -->
		</div>
<div class="wrap flex-c-c">
  <form action="{% url 'zxy:reset_teacher' %}" method="post" class="flex-c-c" onsubmit="return check_reset_t()">
	  {% csrf_token %}
	<h1 class="warning">教师登录页面</h1>
    <ul class="select__list">
      <li id="js-usr-rtn" class="select__label"><a href="{% url 'zxy:login_teacher' %}">登录</a></li>
      <li id="js-usr-new" class="select__label"><a href="{% url 'zxy:register_teacher' %}">注册</a></li>
      <li id="js-usr-rst" class="select__label select__label--active"><a href="{% url 'zxy:reset_teacher' %}">忘记密码</a></li>
    </ul>
    <span class="pointer --usr-rst"></span>
	<input type="text" name="teachername" placeholder="真实姓名" class="ui-field" id="js-field__name" required="required"/>
      <span class="error" id="name_error"></span>
    <input type="number" name="teacherid" placeholder="职工号" class="ui-field" id="js-field__id" required="required"/>
      <span class="error" id="id_error"></span>
	<input type="email" name="teacheremail" placeholder="绑定的邮箱" class="ui-field" id="js-field__email" required="required"/>
      <span class="error" id="email_error"></span>
    <input type="password" name="teacherpaw" placeholder="新密码" class="ui-field" id="js-field__pass" required="required"/>
      <span class="error" id="pass_error"></span>
    <input type="password" placeholder="确认新密码" class="ui-field" id="js-field__r-pass" required="required"/>
      <span class="error" id="r-pass_error"></span>
	  <input type="text" value="" placeholder="请输入验证码（不区分大小写）" class="input-val" required="required">
	  <span class="error text-center" id="vc_error"></span>
	  <canvas class="center-block" id="canvas" width="100" height="30"></canvas>
	        <!-- <button class="btn btn-primary">提交</button> -->
    <button id="js-btn" class="vcbtn ui-button --usr-rst" type="submit"></button>
	<a href="{% url 'zxy:login_student' %}" class="btn btn-primary" id="transfer">进入学生登录页面</a>
  </form>
</div>
<footer class="bs-docs-footer">
		  <div class="container">
		    <ul class="bs-docs-footer-links">
		      <li><a href="http://www.ynu.edu.cn">云南大学</a></li>
		      <li><a href="#">联系我们</a></li>
		      <li><a href="#">关于</a></li>
		    </ul>
			<h4>
			  <strong>智学云——教学办公一体化平台</strong>
			</h4>
		    <p>我们一直致力于为广大师生提供更多的优质服务！</p>
		  </div>
		</footer>

</body>
</html>